sudo: false
matrix:
  include:
  - language: php
    php:
    - 7
    script:
    - ".travis-build/phplint ."
  - language: node.js
    node_js: 10.20.1
before_install:
- npm i -g npm@v6.14.8
install:
- npm install
after_success:
- npm run build
- rm -rf node_modules
- tar -czf volunteer.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  github_token: gfmFfI649E82/WGtfaV6wnVD8bzQLoTS4y33St6iW9KgmKBYKTaifto8sHZVqMyPO3ug1NIV0/HpCuXh7lBUN0/X9kC1ztEVONtjv4A7wswMepcRm55bZWsl2zbHayXKrECmNjvDKKsh8AjNB5iFq+cL8cDrlfsEVoWMpd5r1N/25mh4udPM9fRbaL6bbhKCWmIUhe3mFO1b6Nu2rAQPpOlQRQ+R4psddgCMac4SCvMA/p69Fk3m3fLX8vRvnSKJCbD1hU9B6Kmmcss5FSJnnCo6wsOqJOHLPFO2TJ3XdgjOl4QpiBWJnWe1gwN0SBLDVOLz6nH0jzh+3Eb3wYq84N5/LKv+1QxVnd38dOTqMWYMSGPd92h+FUNnLum/qFGUe9pE2fxBFu6thHNMozUNzulK2+KIaMvmQtHzxnYAu9CzzcMuz+VfPU4lMg0svMOi2otwOhIBkIXKmfSkNb5rHUdYBC1h+kJSQI5D/wzAXy/D5kZvWxghCdu8ocS6q4ngnC751zRLlGPyLE9AXSzfD8H8Mf8/S9qUV/bN83MFgCg8iND/u5R4OxkrWiDGmxalTUGF8mNt5SymcgHRYZxF6douGJpd1oktBuWzTFPhk1ZeFDRHkhnu40Bi4qPGfF2rV01rPO75vEo3CIG4IbdDsbbhVa0IwXxrs1o72jVZ6rE=
  file: volunteer.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/volunteer
    branch: master
    tags: true
